# EmbedShader.cmake
#
# Converts a compiled shader binary or text file into a C++ source file that
# embeds the data as a static byte array.
#
# Usage (cmake -P script mode):
#   cmake -DINPUT=<file> -DOUTPUT=<file.cpp> -DVAR_NAME=<name> -DFORMAT=<SPIRV|MSL> -P EmbedShader.cmake
#
# SPIRV  -- reads a binary .spv file, emits an alignas(4) u8[] array.
# MSL    -- reads a text .msl file, emits a const char[] raw-string literal.

cmake_minimum_required(VERSION 3.21)

if(NOT INPUT OR NOT OUTPUT OR NOT VAR_NAME OR NOT FORMAT)
    message(FATAL_ERROR
        "EmbedShader.cmake requires INPUT, OUTPUT, VAR_NAME, and FORMAT to be defined.\n"
        "Example: cmake -DINPUT=foo.spv -DOUTPUT=foo.cpp -DVAR_NAME=MyShader -DFORMAT=SPIRV -P EmbedShader.cmake")
endif()

get_filename_component(out_dir "${OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${out_dir}")

# ---------------------------------------------------------------------------
# SPIR-V  -- binary blob embedded as an alignas(4) unsigned char array.
# The alignment lets VkShaderModuleCreateInfo.pCode point directly at Data[]
# without a reinterpret_cast alignment violation.
# ---------------------------------------------------------------------------
if(FORMAT STREQUAL "SPIRV")

    file(READ "${INPUT}" raw_hex HEX)

    # Insert 0x prefix and trailing comma after every byte pair.
    string(REGEX REPLACE "([0-9a-fA-F][0-9a-fA-F])" "0x\\1, " bytes "${raw_hex}")

    file(WRITE "${OUTPUT}" "\
// Auto-generated by EmbedShader.cmake -- do not edit.
#include \"Fusion/Misc/CoreTypes.h\"

namespace Fusion::Shaders::Embedded {

alignas(4) static const Fusion::u8 Data[] = { ${bytes} };

const Fusion::u8* ${VAR_NAME}_SPIRV()     { return Data; }
Fusion::SizeT     ${VAR_NAME}_SPIRVSize() { return sizeof(Data); }

} // namespace Fusion::Shaders::Embedded
")

# ---------------------------------------------------------------------------
# MSL  -- text source embedded as a raw-string literal.
# Metal compiles MSL to a MTLLibrary at app initialisation; storing the source
# as text is the correct cross-platform approach.
# ---------------------------------------------------------------------------
elseif(FORMAT STREQUAL "MSL")

    file(READ "${INPUT}" msl_source)

    file(WRITE "${OUTPUT}" "\
// Auto-generated by EmbedShader.cmake -- do not edit.
#include \"Fusion/Misc/CoreTypes.h\"

namespace Fusion::Shaders::Embedded {

static const char Data[] = R\"FUSION_MSL_END(
${msl_source}
)FUSION_MSL_END\";

const char*   ${VAR_NAME}_MSL()     { return Data; }
Fusion::SizeT ${VAR_NAME}_MSLSize() { return sizeof(Data) - 1; }

} // namespace Fusion::Shaders::Embedded
")

else()
    message(FATAL_ERROR "EmbedShader.cmake: Unknown FORMAT '${FORMAT}'. Expected SPIRV or MSL.")
endif()
