#pragma once

#include "Fusion/Resources/ResourceTypes.h"

namespace Fusion::Resources
{

    // Returns the resource at exactly <path>, or nullptr if not found.
    // O(log n) — binary search over the sorted resource array.
    //
    // Example:
    //   const auto* font = Fusion::Resources::Find("/Fonts/Roboto.ttf");
    const FResource* Find(const char* path);

    // Returns a view over every resource whose virtual path begins with <folderPath>.
    // <folderPath> must start with '/' and end with '/' (use "/" to list everything).
    // The view is a contiguous sub-range of the sorted internal array — no allocation.
    // O(log n + k) where k is the number of matching resources.
    //
    // Examples:
    //   for (const auto& r : Fusion::Resources::ListAll("embed:/Fonts/")) { ... }
    //   for (const auto& r : Fusion::Resources::ListAll("embed:/"))       { ... } // all resources
    FResourceView ListAll(const char* folderPath = "embed:/");

} // namespace Fusion::Resources


// ---- Internal — generated by ResourceRegistry.cpp, not for direct use ----
namespace Fusion::Resources::Internal
{
    const FResource* GetData();
    SizeT            GetCount();
} // namespace Fusion::Resources::Internal
