# -------------------------------------------------------------------------------------------------
# fusion_embed_resources_dir(TARGET <target> DIR <dir> [BASE_PATH <path>])
#
#   Embeds every file found recursively under DIR into <target> as C++ byte arrays.
#   Each file is accessible at the virtual path: BASE_PATH + relative-path-from-DIR.
#
#   BASE_PATH defaults to "/" and must start with "/".
#   Example: DIR = ${CMAKE_CURRENT_SOURCE_DIR}/Resources, BASE_PATH = "/"
#     Resources/Fonts/Roboto.ttf  →  virtual path "/Fonts/Roboto.ttf"
#
#   Adding or removing files from DIR triggers a CMake re-configure automatically
#   (via CONFIGURE_DEPENDS), which regenerates the registry.
#
# fusion_finalize_resource_registry(<target>)
#
#   Generates ResourceRegistry.cpp containing the sorted resource array and the
#   Internal::GetData() / Internal::GetCount() accessors used by EmbeddedResources.cpp.
#   Must be called exactly once, after all fusion_embed_resources_dir() calls for <target>.
# -------------------------------------------------------------------------------------------------

function(fusion_embed_resources_dir)
    cmake_parse_arguments(ARG "" "TARGET;DIR;BASE_PATH" "" ${ARGN})

    if(NOT ARG_TARGET)
        message(FATAL_ERROR "fusion_embed_resources_dir: TARGET is required.")
    endif()
    if(NOT ARG_DIR)
        message(FATAL_ERROR "fusion_embed_resources_dir: DIR is required.")
    endif()
    if(NOT DEFINED ARG_BASE_PATH)
        set(ARG_BASE_PATH "/")
    endif()

    # Normalise BASE_PATH: strip any leading/trailing slashes, then re-wrap with exactly one each.
    # Avoids regex zero-length-match edge cases that can produce double slashes.
    string(REGEX REPLACE "^/+" "" _base "${ARG_BASE_PATH}")
    string(REGEX REPLACE "/+$" "" _base "${_base}")
    if(_base STREQUAL "")
        set(ARG_BASE_PATH "/")
    else()
        set(ARG_BASE_PATH "/${_base}/")
    endif()
    unset(_base)

    file(GLOB_RECURSE all_files CONFIGURE_DEPENDS "${ARG_DIR}/*")

    foreach(abs_file IN LISTS all_files)
        if(IS_DIRECTORY "${abs_file}")
            continue()
        endif()

        # Relative path from the resource root directory
        file(RELATIVE_PATH rel_path "${ARG_DIR}" "${abs_file}")
        string(REPLACE "\\" "/" rel_path "${rel_path}")

        # Virtual path seen at runtime (e.g. "/Fonts/Roboto.ttf").
        # BASE_PATH is already normalized to end with '/', so plain concatenation is correct.
        set(virtual_path "${ARG_BASE_PATH}${rel_path}")

        # C++ identifier: replace every non-alphanumeric character with '_'
        string(REGEX REPLACE "[^a-zA-Z0-9]" "_" var_name "${rel_path}")

        set(output_cpp "${CMAKE_CURRENT_BINARY_DIR}/Generated/Resources/${var_name}.cpp")
        get_filename_component(output_dir "${output_cpp}" DIRECTORY)
        file(MAKE_DIRECTORY "${output_dir}")

        add_custom_command(
            OUTPUT  "${output_cpp}"
            COMMAND ${CMAKE_COMMAND}
                    -DINPUT=${abs_file}
                    -DOUTPUT=${output_cpp}
                    -DVAR_NAME=${var_name}
                    -P ${CMAKE_SOURCE_DIR}/CMake/Scripts/EmbedResource.cmake
            DEPENDS "${abs_file}"
                    "${CMAKE_SOURCE_DIR}/CMake/Scripts/EmbedResource.cmake"
            COMMENT "Embedding resource ${virtual_path}"
            VERBATIM
        )

        target_sources(${ARG_TARGET} PRIVATE "${output_cpp}")

        # Accumulate parallel lists: paths and their corresponding C++ var names.
        # These are consumed by fusion_finalize_resource_registry().
        set_property(TARGET ${ARG_TARGET} APPEND PROPERTY FUSION_RESOURCE_PATHS    "${virtual_path}")
        set_property(TARGET ${ARG_TARGET} APPEND PROPERTY FUSION_RESOURCE_VARNAMES "${var_name}")
    endforeach()
endfunction()


function(fusion_finalize_resource_registry target)
    get_property(paths    TARGET ${target} PROPERTY FUSION_RESOURCE_PATHS)
    get_property(varnames TARGET ${target} PROPERTY FUSION_RESOURCE_VARNAMES)

    # Sort paths lexicographically — this order must match strcmp() used at runtime.
    set(sorted_paths ${paths})
    if(sorted_paths)
        list(SORT sorted_paths COMPARE STRING CASE SENSITIVE)
    endif()

    set(out_dir "${CMAKE_CURRENT_BINARY_DIR}/Generated")
    set(out     "${out_dir}/ResourceRegistry.cpp")
    file(MAKE_DIRECTORY "${out_dir}")

    # ---- Begin generated file ----
    set(content "// Auto-generated by Resources.cmake -- do not edit.\n")
    string(APPEND content "#include \"Fusion/Resources/EmbeddedResources.h\"\n\n")

    if(sorted_paths)
        # Forward-declare every per-file accessor (defined in the build-time generated .cpp files).
        string(APPEND content "namespace Fusion::Resources::Embedded\n{\n")
        foreach(path IN LISTS sorted_paths)
            list(FIND paths "${path}" idx)
            list(GET varnames ${idx} vname)
            string(APPEND content "    extern const Fusion::u8* Res_${vname}();\n")
            string(APPEND content "    extern Fusion::SizeT     Res_${vname}_Size();\n")
        endforeach()
        string(APPEND content "} // namespace Fusion::Resources::Embedded\n\n")

        # Sorted resource array. Order here is the binary-search contract used by Find().
        string(APPEND content "namespace Fusion::Resources::Internal\n{\n\n")
        string(APPEND content "static const ::Fusion::Resources::FResource s_Resources[] =\n{\n")
        foreach(path IN LISTS sorted_paths)
            list(FIND paths "${path}" idx)
            list(GET varnames ${idx} vname)
            string(APPEND content "    { \"embed:${path}\", Embedded::Res_${vname}(), Embedded::Res_${vname}_Size() },\n")
        endforeach()
        string(APPEND content "};\n\n")

        string(APPEND content "const ::Fusion::Resources::FResource* GetData()  { return s_Resources; }\n")
        string(APPEND content "::Fusion::SizeT                       GetCount() { return sizeof(s_Resources) / sizeof(s_Resources[0]); }\n\n")
    else()
        # No resources registered — emit stubs so the target still compiles.
        string(APPEND content "namespace Fusion::Resources::Internal\n{\n\n")
        string(APPEND content "const ::Fusion::Resources::FResource* GetData()  { return nullptr; }\n")
        string(APPEND content "::Fusion::SizeT                       GetCount() { return 0; }\n\n")
    endif()

    string(APPEND content "} // namespace Fusion::Resources::Internal\n")
    # ---- End generated file ----

    file(WRITE "${out}" "${content}")
    target_sources(${target} PRIVATE "${out}")
endfunction()
